<div class="md:text-6xl text-2xl font-bold uppercase absolute right-7 text-right text-purple-900">
    <h2>
        Escape
    </h2>
    <h2>
        Into
    </h2>
    <h2>
        The
    </h2>
    <h2>
        Now-Known
    </h2>
</div>
<div class="md:text-6xl text-2xl font-bold uppercase absolute right-5 text-right text-blue-900">
    <h2>
        Escape
    </h2>
    <h2>
        Into
    </h2>
    <h2>
        The
    </h2>
    <h2>
        Now-Known
    </h2>
</div>
<div class="md:text-6xl text-2xl font-bold uppercase absolute right-6 text-right">
    <h2>
        Escape
    </h2>
    <h2>
        Into
    </h2>
    <h2>
        The
    </h2>
    <h2>
        Now-Known
    </h2>
</div>
