<x-layout>
    <x-top-header></x-top-header>
    <x-hero></x-hero>
    <x-introduction></x-introduction>
    <x-vision></x-vision>
    <x-mission></x-mission>
    <x-map></x-map>
    <x-footer></x-footer>
</x-layout>