http://localhost:8000/api/pets
Content-Type: application/json
Authorization: Bearer 1|ZrDGUSeKjh8EocbBzUVVqowzQq1oLslCzXd4qaAM

###
POST http://localhost:8000/api/pets/add-to-fav
Content-Type: application/json
Authorization: Bearer 1|ZrDGUSeKjh8EocbBzUVVqowzQq1oLslCzXd4qaAM

{
    "pet_id": 1
}

###
POST https://secaspi.elezerk.net/api/login
Content-Type: application/json

{
    "email": "williamgalas2@gmail.com",
    "password": "password"
}

###
http://localhost:8000/api/conversations/me
Content-Type: application/json
Authorization: Bearer 1|ZrDGUSeKjh8EocbBzUVVqowzQq1oLslCzXd4qaAM

###
POST https://secaspi.elezerk.net/api/conversations
Content-Type: application/json
Authorization: Bearer 25|OSCDtUYMYLczJHwH1DkfOUiveyEns1MmR3J6Q0zs

{
    "name": "Adopt Bentexx"
}
