<template>
    <div>
        <a-alert message="Reminders" description="The grades generated by this system are official and based on the class record. Any errors should be reported to the instructor or academic department for review and correction.
" type="info" show-icon />
        <div class="mt-2"></div>
        <a-card>
            <div slot="title">
                FINAL GRADE
            </div>
            <div slot="extra">
                <a-button type="primary" @click="generate" :loading="generating">
                    <a-icon type="thunderbolt" />
                    GENERATE
                </a-button>
            </div>
            <a-table :key="tableKey" bordered :scroll="{ x: true }" size="small" :columns="columns"
                :data-source="load.student_records">
                <div slot="no" slot-scope="item, record, index">
                    {{ index + 1 }}
                </div>
                <div slot="prelim" slot-scope="item, record">
                    <editable-cell :text="item" @change="cellChange(record, $event, 'prelim_grade')"></editable-cell>
                </div>
                <div slot="midterm" slot-scope="item, record">
                    <editable-cell :text="item" @change="cellChange(record, $event, 'midterm_grade')"></editable-cell>
                </div>
                <div slot="prefinal" slot-scope="item, record">
                    <editable-cell :text="item" @change="cellChange(record, $event, 'pre_final_grade')"></editable-cell>
                </div>
                <div slot="final" slot-scope="item, record">
                    <editable-cell :text="item" @change="cellChange(record, $event, 'final_grade')"></editable-cell>
                </div>
                <div slot="total" slot-scope="item, record">
                    <editable-cell :text="item" @change="cellChange(record, $event, 'total_grade')"></editable-cell>
                </div>
                <div slot="remark" slot-scope="item, record">
                    <editable-cell :text="item" @change="cellChange(record, $event, 'remarks')"></editable-cell>
                </div>

            </a-table>
        </a-card>
    </div>
</template>

<script>

import EditableCell from './EditableCell.vue';
export default {
    components: {
        EditableCell,
    },
    props: ['load'],
    methods: {
        async cellChange(record, newValue, prop) {
            record[prop] = newValue;
            await axios.post('/nova-vendor/sections/update-record/' + record.id, { ...record });
        },
        async generate() {
            this.generating = true;
            await axios.post('/nova-vendor/sections/generate-grade/' + this.load.id);
            this.$notification.success({ message: 'success', description: 'Grade has been generated successfully' });
            this.$emit('reload')
            this.generating = false;
            this.tableKey = this.tableKey++;
        }
    },
    data() {
        return {
            tableKey: 1,
            grades: [],
            generating: false,
            columns: [
                {
                    title: 'No.',
                    key: 'no',
                    scopedSlots: { customRender: 'no' },
                },
                {
                    title: 'Student',
                    key: 'name',
                    dataIndex: 'student.name',
                },
                {
                    title: 'Student No.',
                    key: 'number',
                    dataIndex: 'student.profile.number',
                },
                {
                    title: 'Prelim',
                    key: 'prelim',
                    dataIndex: 'prelim_grade',
                    scopedSlots: { customRender: 'prelim' },
                },
                {
                    title: 'Midterm',
                    key: 'midterm',
                    dataIndex: 'midterm_grade',
                    scopedSlots: { customRender: 'midterm' },
                },
                {
                    title: 'Pre-Final',
                    key: 'pre_final',
                    dataIndex: 'pre_final_grade',
                    scopedSlots: { customRender: 'prefinal' },
                },
                {
                    title: 'Final',
                    key: 'final',
                    dataIndex: 'final_grade',
                    scopedSlots: { customRender: 'final' },
                },
                {
                    title: 'Final Grade',
                    key: 'total_grade',
                    dataIndex: 'total_grade',
                    scopedSlots: { customRender: 'total' },
                },
                {
                    title: 'Remarks',
                    key: 'remarks',
                    dataIndex: 'remarks',
                    scopedSlots: { customRender: 'remark' },
                },
            ],
        }
    }
}
</script>
